name: Model Training CICD
permissions:
  id-token: write
  contents: write 

on:
  - push

jobs:
  run:
    runs-on: 
      - ubuntu-latest
    
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run training script
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run the train_model.py script (make sure it saves the images)
          python train_model.py

      - name: Create reports
        run: |
          echo "RF and LR Model Score" > report.md
          cat scores.txt >> report.md
          
          echo "Confusion Matrix & Feature Importance" > report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md
     
          # Combine both report files into one
          cat report.md report1.md >> combined_file.md

          # Use CML to comment on the combined report
          cml comment create combined_file.md
